# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160821_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'bucketlist-images', verbose_name=b'Bucket List Image'),
        ),
    ]
