# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 18:38
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bucketlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='slug',
            field=autoslug.fields.AutoSlugField(),
        ),
    ]
