# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 18:39
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160821_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'title'),
        ),
    ]
